### PR TITLE
Initial stab at Bazel rules for rjsone

### PR DESCRIPTION
**Pull request by ash2k**
`bazel build //examples/basic:example1` produces two files:
```console
INFO: Analysed target //examples/basic:example1 (0 packages loaded).
INFO: Found 1 target...
Target //examples/basic:example1 up-to-date:
  bazel-bin/examples/basic/example1.yaml
  bazel-bin/examples/basic/example1.json
INFO: Elapsed time: 0.248s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```
Individual outputs can be addressed like this (only the referenced one is built, not both):
`bazel build //examples/basic:example1.yaml` to get YAML
`bazel build //examples/basic:example1.json` to get JSON.

### CODE REVIEW

**Comment by ash2k** [comment]
This implementation does not support all the functionality, but just shows that it is possible to build a wrapper for Bazel.

**Comment by ash2k** [comment]
Ok, this needs a bit more tweaking to make it useable from outside from this repo... working on it.

**Comment by wryun** [comment]
Wow, you did it ;)

I'm not convinced we want these rules in the rjsone repo, though... does it offer advantages?

**Comment by wryun** [comment]
(also, not clear if this is 'working' now ... err, really should write some tests)

**Comment by ash2k** [comment]
> I'm not convinced we want these rules in the rjsone repo, though... does it offer advantages?

No advantages. Can live anywhere - it can depend on a particular commit of rjsone.

Yes, tests is something that is needed. Both for Go code and for the wrapping rules.

**Pull request closed without merging**
